// AUTO-GENERATED by scripts/process-cutout-images.mjs — do not edit by hand.
// Processed cutout images (transparent WebP, 960x1200, 4:5).
// Product name + slug are derived from each source file name.

export type ProductImage = {
  brandSlug: string;
  productName: string;
  productSlug: string;
  imagePath: string;
};

export const productImages: ProductImage[] = [
  { brandSlug: "a-v-vattev", productName: "O'keeffe Studded T Shirt Black", productSlug: "o-keeffe-studded-t-shirt-black", imagePath: "/products/a-v-vattev/o-keeffe-studded-t-shirt-black.webp" },
  { brandSlug: "a-v-vattev", productName: "Scarf Shirt Patchwork Black", productSlug: "scarf-shirt-patchwork-black", imagePath: "/products/a-v-vattev/scarf-shirt-patchwork-black.webp" },
  { brandSlug: "abelia-edoward-goucha", productName: "Aeg Cap Straight", productSlug: "aeg-cap-straight", imagePath: "/products/abelia-edoward-goucha/aeg-cap-straight.webp" },
  { brandSlug: "abelia-edoward-goucha", productName: "Double Belt Pants", productSlug: "double-belt-pants", imagePath: "/products/abelia-edoward-goucha/double-belt-pants.webp" },
  { brandSlug: "abelia-edoward-goucha", productName: "Ordinary Shirt Chino", productSlug: "ordinary-shirt-chino", imagePath: "/products/abelia-edoward-goucha/ordinary-shirt-chino.webp" },
  { brandSlug: "abelia-edoward-goucha", productName: "Sun Hoodie", productSlug: "sun-hoodie", imagePath: "/products/abelia-edoward-goucha/sun-hoodie.webp" },
  { brandSlug: "commission", productName: "Curve Flap Jacket, Heather Grey", productSlug: "curve-flap-jacket-heather-grey", imagePath: "/products/commission/curve-flap-jacket-heather-grey.webp" },
  { brandSlug: "commission", productName: "Dress", productSlug: "dress", imagePath: "/products/commission/dress.webp" },
  { brandSlug: "edward-cuming", productName: "Bottom Heavy Top Heavy Bomber", productSlug: "bottom-heavy-top-heavy-bomber", imagePath: "/products/edward-cuming/bottom-heavy-top-heavy-bomber.webp" },
  { brandSlug: "edward-cuming", productName: "Drop Dart Volume Jean", productSlug: "drop-dart-volume-jean", imagePath: "/products/edward-cuming/drop-dart-volume-jean.webp" },
  { brandSlug: "edward-cuming", productName: "Encompassing Vortex Skirt", productSlug: "encompassing-vortex-skirt", imagePath: "/products/edward-cuming/encompassing-vortex-skirt.webp" },
  { brandSlug: "edward-cuming", productName: "Thong Sandal Mens", productSlug: "thong-sandal-mens", imagePath: "/products/edward-cuming/thong-sandal-mens.webp" },
  { brandSlug: "gabriela-coll-garments", productName: "No.216 Ripstop Hooded Zipper Jacket, Off Black", productSlug: "no-216-ripstop-hooded-zipper-jacket-off-black", imagePath: "/products/gabriela-coll-garments/no-216-ripstop-hooded-zipper-jacket-off-black.webp" },
  { brandSlug: "gabriela-coll-garments", productName: "No.297 Leather Small Crossed Bag, Black", productSlug: "no-297-leather-small-crossed-bag-black", imagePath: "/products/gabriela-coll-garments/no-297-leather-small-crossed-bag-black.webp" },
  { brandSlug: "gabriela-coll-garments", productName: "No.304 Linen Wrap Skirt, Black", productSlug: "no-304-linen-wrap-skirt-black", imagePath: "/products/gabriela-coll-garments/no-304-linen-wrap-skirt-black.webp" },
  { brandSlug: "gabriela-coll-garments", productName: "No.317 Organic Cotton Fleece Top, Black", productSlug: "no-317-organic-cotton-fleece-top-black", imagePath: "/products/gabriela-coll-garments/no-317-organic-cotton-fleece-top-black.webp" },
  { brandSlug: "gimaguas", productName: "Bailarina Wedges Black Silueta 01", productSlug: "bailarina-wedges-black-silueta-01", imagePath: "/products/gimaguas/bailarina-wedges-black-silueta-01.webp" },
  { brandSlug: "gimaguas", productName: "Daniel Jacket Grey Silueta", productSlug: "daniel-jacket-grey-silueta", imagePath: "/products/gimaguas/daniel-jacket-grey-silueta.webp" },
  { brandSlug: "gimaguas", productName: "Daria Top Black Silueta", productSlug: "daria-top-black-silueta", imagePath: "/products/gimaguas/daria-top-black-silueta.webp" },
  { brandSlug: "gimaguas", productName: "Ingrid Mini Dress Black Silueta", productSlug: "ingrid-mini-dress-black-silueta", imagePath: "/products/gimaguas/ingrid-mini-dress-black-silueta.webp" },
  { brandSlug: "gimaguas", productName: "Luis Ls Polo Grey Silueta", productSlug: "luis-ls-polo-grey-silueta", imagePath: "/products/gimaguas/luis-ls-polo-grey-silueta.webp" },
  { brandSlug: "helmut-lang", productName: "Chino Pant", productSlug: "chino-pant", imagePath: "/products/helmut-lang/chino-pant.webp" },
  { brandSlug: "helmut-lang", productName: "Funnel Neck Pullover", productSlug: "funnel-neck-pullover", imagePath: "/products/helmut-lang/funnel-neck-pullover.webp" },
  { brandSlug: "helmut-lang", productName: "Knot Shirt Dress", productSlug: "knot-shirt-dress", imagePath: "/products/helmut-lang/knot-shirt-dress.webp" },
  { brandSlug: "helmut-lang", productName: "Twisted Shirt Dress", productSlug: "twisted-shirt-dress", imagePath: "/products/helmut-lang/twisted-shirt-dress.webp" },
  { brandSlug: "johanna-parv", productName: "Cover Skirt, Khaki", productSlug: "cover-skirt-khaki", imagePath: "/products/johanna-parv/cover-skirt-khaki.webp" },
  { brandSlug: "johanna-parv", productName: "Skirt Capris, Black", productSlug: "skirt-capris-black", imagePath: "/products/johanna-parv/skirt-capris-black.webp" },
  { brandSlug: "kiko-kostadinov", productName: "Kiko Kostadinov X Dr. Martens The Toe Box Shoe Moss Green", productSlug: "kiko-kostadinov-x-dr-martens-the-toe-box-shoe-moss-green", imagePath: "/products/kiko-kostadinov/kiko-kostadinov-x-dr-martens-the-toe-box-shoe-moss-green.webp" },
  { brandSlug: "kiko-kostadinov", productName: "Ostro Canvas Shoes Beech Orange", productSlug: "ostro-canvas-shoes-beech-orange", imagePath: "/products/kiko-kostadinov/ostro-canvas-shoes-beech-orange.webp" },
  { brandSlug: "kiko-kostadinov", productName: "Reticella Ballerina Sapphire", productSlug: "reticella-ballerina-sapphire", imagePath: "/products/kiko-kostadinov/reticella-ballerina-sapphire.webp" },
  { brandSlug: "kiko-kostadinov", productName: "Sargo Shoes Umber", productSlug: "sargo-shoes-umber", imagePath: "/products/kiko-kostadinov/sargo-shoes-umber.webp" },
  { brandSlug: "lea-boberg", productName: "Sc Shirt", productSlug: "sc-shirt", imagePath: "/products/lea-boberg/sc-shirt.webp" },
  { brandSlug: "mainline", productName: "Ilya", productSlug: "ilya", imagePath: "/products/mainline/ilya.webp" },
  { brandSlug: "meta-campania-collective", productName: "Jacket", productSlug: "jacket", imagePath: "/products/meta-campania-collective/jacket.webp" },
  { brandSlug: "natasha-zinko", productName: "Bunny Bag", productSlug: "bunny-bag", imagePath: "/products/natasha-zinko/bunny-bag.webp" },
  { brandSlug: "natasha-zinko", productName: "Double Tshirt", productSlug: "double-tshirt", imagePath: "/products/natasha-zinko/double-tshirt.webp" },
  { brandSlug: "natasha-zinko", productName: "Oversized Double Polo", productSlug: "oversized-double-polo", imagePath: "/products/natasha-zinko/oversized-double-polo.webp" },
  { brandSlug: "paloma-wool", productName: "Lonati, Denim", productSlug: "lonati-denim", imagePath: "/products/paloma-wool/lonati-denim.webp" },
  { brandSlug: "paloma-wool", productName: "Penelope Ii, Black", productSlug: "penelope-ii-black", imagePath: "/products/paloma-wool/penelope-ii-black.webp" },
  { brandSlug: "paloma-wool", productName: "Simulet, Brown", productSlug: "simulet-brown", imagePath: "/products/paloma-wool/simulet-brown.webp" },
  { brandSlug: "ponder-er", productName: "Dash Crossbody Denim Bag (Blue)~mv2", productSlug: "dash-crossbody-denim-bag-blue-mv2", imagePath: "/products/ponder-er/dash-crossbody-denim-bag-blue-mv2.webp" },
  { brandSlug: "ponder-er", productName: "Ravel Spiral Smocked Denim Skirt (White)", productSlug: "ravel-spiral-smocked-denim-skirt-white", imagePath: "/products/ponder-er/ravel-spiral-smocked-denim-skirt-white.webp" },
  { brandSlug: "ponder-er", productName: "Voya Faux Shearling Jacket (Black)", productSlug: "voya-faux-shearling-jacket-black", imagePath: "/products/ponder-er/voya-faux-shearling-jacket-black.webp" },
  { brandSlug: "super-yaya", productName: "Syy X Puma Speedcat Ii Black", productSlug: "syy-x-puma-speedcat-ii-black", imagePath: "/products/super-yaya/syy-x-puma-speedcat-ii-black.webp" },
  { brandSlug: "super-yaya", productName: "Winona Knit Polo Tee, Brown Purple", productSlug: "winona-knit-polo-tee-brown-purple", imagePath: "/products/super-yaya/winona-knit-polo-tee-brown-purple.webp" },
  { brandSlug: "umber-postpast", productName: "Cotton Organza Layered Midi Dress", productSlug: "cotton-organza-layered-midi-dress", imagePath: "/products/umber-postpast/cotton-organza-layered-midi-dress.webp" },
  { brandSlug: "umber-postpast", productName: "Natural Dyed Silk Trench Coat", productSlug: "natural-dyed-silk-trench-coat", imagePath: "/products/umber-postpast/natural-dyed-silk-trench-coat.webp" },
  { brandSlug: "umber-postpast", productName: "Wool Gauze Boat Neck Long Dress", productSlug: "wool-gauze-boat-neck-long-dress", imagePath: "/products/umber-postpast/wool-gauze-boat-neck-long-dress.webp" }
];
